### ISSUE TITLE
Unconsistent consumption values 

### ISSUE THREAD

**Issue by chaboden** [innoTUgrid/backend#68]
Total consumption 2019

http://localhost:3000/v1/kpi/consumption/?from=2019-01-01T00:00:00.000Z&to=2019-12-31T23:59:59.999Z&interval=1month&source=IPCC
--> 2.842.898,03 (aggregiert gri report page) 
http://localhost:3000/v1/kpi/total_consumption/?from=2018-12-31T23:00:00.000Z&to=2019-12-31T22:59:59.999Z&interval=1month
--> 2579665.5 (overview kpi)

**Comment by OleFass** [comment]
Related to #65 
The reason for the behaviour is that the `consumption` endpoint calculates its result by adding up all consumers where as the `total_consumption` endpoint simply sums up all entries of `total_load`. Since in the data `total_load` is not equal the sum of energy consumed by all consumers there is a difference in the data returned by both endpoints.
